services:
  - type: web
    name: sistema-alumnos
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn sistema_alumnos.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sistema-alumnos
          property: connectionString
      - key: PYTHONUNBUFFERED
        value: true
